# Generated by Django 3.1.7 on 2021-02-23 21:02

import billing.models.proxy_user
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified_at', verbose_name='modified_at')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='balance', max_digits=24, verbose_name='balance')),
                ('user', models.OneToOneField(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'billing.accounts',
            },
        ),
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', billing.models.proxy_user.ProxyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified_at', verbose_name='modified_at')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='amount', max_digits=24, verbose_name='amount')),
                ('from_account', models.ForeignKey(help_text='from_account', on_delete=django.db.models.deletion.PROTECT, related_name='from_transfers', to='billing.account', verbose_name='from_account')),
                ('to_account', models.ForeignKey(help_text='to_account', on_delete=django.db.models.deletion.PROTECT, related_name='to_transfers', to='billing.account', verbose_name='to_account')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transfers',
                'verbose_name_plural': 'transfers',
                'db_table': 'billing.transfers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified_at', verbose_name='modified_at')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='amount', max_digits=24, verbose_name='amount')),
                ('account', models.ForeignKey(help_text='account', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.account', verbose_name='account')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'billing.payments',
            },
        ),
    ]
